# Generated by Django 5.2.1 on 2025-06-03 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teachers', '0003_teacher_address_teacher_blood_group_teacher_phone_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='photo_url',
            field=models.URLField(blank=True, help_text="External URL for teacher's photo", null=True),
        ),
    ]
